# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blfdr_fn <- function(u_main, unif_dat, eta1, eta2, eta3, eta4, extraParam) {
    .Call(`_zap_blfdr_fn`, u_main, unif_dat, eta1, eta2, eta3, eta4, extraParam)
}

blfdr_stat <- function(U, eta1, eta2, eta3, eta4, extraParam) {
    .Call(`_zap_blfdr_stat`, U, eta1, eta2, eta3, eta4, extraParam)
}

trunc_log_arma <- function(U) {
    .Call(`_zap_trunc_log_arma`, U)
}

createParaMat <- function(param, X_tilde) {
    .Call(`_zap_createParaMat`, param, X_tilde)
}

form_Hmat_unmask <- function(U, paraMat, extraParam) {
    .Call(`_zap_form_Hmat_unmask`, U, paraMat, extraParam)
}

form_Hmat_unmask_init <- function(U, beta0, piMat, X_tilde, extraParam) {
    .Call(`_zap_form_Hmat_unmask_init`, U, beta0, piMat, X_tilde, extraParam)
}

form_Hmat_Yab_mask_init <- function(U_mask, U_mirror_mask, beta0, piMat, X_tilde, extraParam) {
    .Call(`_zap_form_Hmat_Yab_mask_init`, U_mask, U_mirror_mask, beta0, piMat, X_tilde, extraParam)
}

form_Hmat_Yab_mask <- function(U_mask, U_mirror_mask, paraMat, extraParam) {
    .Call(`_zap_form_Hmat_Yab_mask`, U_mask, U_mirror_mask, paraMat, extraParam)
}

overall_Hmat <- function(Hmat_mask, Hmat_unmask, mask_set, unmask_set) {
    .Call(`_zap_overall_Hmat`, Hmat_mask, Hmat_unmask, mask_set, unmask_set)
}

overall_Ymat <- function(Ymat_mask, U_unmask, mask_set, unmask_set) {
    .Call(`_zap_overall_Ymat`, Ymat_mask, U_unmask, mask_set, unmask_set)
}

neg_LogLike_LeftBeta <- function(beta_l, U, X_tilde, gamma_l) {
    .Call(`_zap_neg_LogLike_LeftBeta`, beta_l, U, X_tilde, gamma_l)
}

neg_LogLike_LeftBeta_grad <- function(beta_l, U, X_tilde, gamma_l) {
    .Call(`_zap_neg_LogLike_LeftBeta_grad`, beta_l, U, X_tilde, gamma_l)
}

neg_LogLike_RightBeta <- function(beta_r, U, X_tilde, gamma_r) {
    .Call(`_zap_neg_LogLike_RightBeta`, beta_r, U, X_tilde, gamma_r)
}

neg_LogLike_RightBeta_grad <- function(beta_r, U, X_tilde, gamma_r) {
    .Call(`_zap_neg_LogLike_RightBeta_grad`, beta_r, U, X_tilde, gamma_r)
}

LogLike_asymp <- function(U, paraMat, extraParam) {
    .Call(`_zap_LogLike_asymp`, U, paraMat, extraParam)
}

neg_Q_fn_finite_beta_part <- function(param_beta, Ymat, Hmat, extraParam, X_tilde) {
    .Call(`_zap_neg_Q_fn_finite_beta_part`, param_beta, Ymat, Hmat, extraParam, X_tilde)
}

neg_Q_fn_finite_beta_part_grad_cpp <- function(param_beta, Ymat, Hmat, extraParam, X_tilde) {
    .Call(`_zap_neg_Q_fn_finite_beta_part_grad_cpp`, param_beta, Ymat, Hmat, extraParam, X_tilde)
}

